-- ============================================================================
-- RAG-POWERED INTELLIGENCE SYSTEM
-- ============================================================================
-- Instead of pre-computing metrics, we run actual RAG searches nightly and
-- store the AI-generated insights with their source documents.
--
-- Philosophy: Use your RAG system to answer real business questions, not just
-- count documents. Store the answers with sources so users can drill down.
-- ============================================================================

-- ============================================================================
-- INTELLIGENCE INSIGHTS (RAG search results with sources)
-- ============================================================================
-- Generated by nightly cron job that runs predefined queries against RAG system
-- Each row = one AI-generated insight with source documents

CREATE TABLE IF NOT EXISTS intelligence_insights (
    id BIGSERIAL PRIMARY KEY,
    tenant_id TEXT NOT NULL,

    -- Time bucketing
    insight_date DATE NOT NULL,  -- Which day this insight is for
    time_period TEXT NOT NULL,   -- 'daily', 'weekly', 'monthly'

    -- The query that was run
    search_query TEXT NOT NULL,  -- e.g. "What deals are progressing this week?"
    query_category TEXT NOT NULL,  -- e.g. 'deals', 'customers', 'issues', 'opportunities'

    -- The AI-generated result
    ai_answer TEXT NOT NULL,  -- GPT-4o-mini's response
    confidence_score DECIMAL(3,2),  -- 0.0 to 1.0 if available

    -- Source documents (for drill-down)
    source_documents JSONB DEFAULT '[]',  -- [{"doc_id": "...", "chunk_text": "...", "score": 0.95}, ...]
    total_sources INTEGER DEFAULT 0,

    -- Metadata
    generated_at TIMESTAMPTZ DEFAULT NOW(),
    generation_duration_ms INTEGER,
    model_used TEXT DEFAULT 'gpt-4o-mini',

    -- Allow re-running stale insights
    is_stale BOOLEAN DEFAULT FALSE,

    UNIQUE(tenant_id, insight_date, search_query)
);

CREATE INDEX idx_intelligence_insights_tenant ON intelligence_insights(tenant_id);
CREATE INDEX idx_intelligence_insights_date ON intelligence_insights(insight_date DESC);
CREATE INDEX idx_intelligence_insights_tenant_date ON intelligence_insights(tenant_id, insight_date DESC);
CREATE INDEX idx_intelligence_insights_category ON intelligence_insights(query_category);
CREATE INDEX idx_intelligence_insights_period ON intelligence_insights(time_period);

COMMENT ON TABLE intelligence_insights IS 'RAG-generated business insights with source documents for drill-down';
COMMENT ON COLUMN intelligence_insights.search_query IS 'The question asked to the RAG system';
COMMENT ON COLUMN intelligence_insights.ai_answer IS 'GPT-4o-mini generated response';
COMMENT ON COLUMN intelligence_insights.source_documents IS 'Array of source chunks with scores for drill-down';
COMMENT ON COLUMN intelligence_insights.query_category IS 'Category for grouping insights (deals, customers, issues, etc.)';


-- ============================================================================
-- PREDEFINED SEARCH QUERIES (what to ask the RAG system)
-- ============================================================================
-- Defines the business questions to ask nightly

CREATE TABLE IF NOT EXISTS intelligence_search_queries (
    id BIGSERIAL PRIMARY KEY,

    -- Query definition
    query_text TEXT NOT NULL,  -- e.g. "What deals or opportunities were discussed?"
    query_category TEXT NOT NULL,  -- 'deals', 'customers', 'issues', 'opportunities', 'summary'
    time_period TEXT NOT NULL,  -- 'daily', 'weekly', 'monthly'

    -- Display configuration
    display_title TEXT NOT NULL,  -- e.g. "Deal Momentum"
    display_icon TEXT,  -- Icon name for frontend
    display_order INTEGER DEFAULT 0,  -- Sort order on dashboard

    -- Query behavior
    is_active BOOLEAN DEFAULT TRUE,
    priority INTEGER DEFAULT 5,  -- 1-10, determines search quality vs speed tradeoff
    max_sources INTEGER DEFAULT 5,  -- How many source docs to include

    -- Scheduling
    run_schedule TEXT DEFAULT 'daily',  -- 'daily', 'weekly', 'monthly', 'on-demand'
    last_run_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_search_queries_active ON intelligence_search_queries(is_active, time_period);
CREATE INDEX idx_search_queries_schedule ON intelligence_search_queries(run_schedule);

COMMENT ON TABLE intelligence_search_queries IS 'Predefined business questions to ask the RAG system nightly';
COMMENT ON COLUMN intelligence_search_queries.priority IS 'Higher priority = better search quality (but slower/more expensive)';


-- ============================================================================
-- SEED DATA: Default business intelligence queries
-- ============================================================================

INSERT INTO intelligence_search_queries (query_text, query_category, time_period, display_title, display_icon, display_order, priority, max_sources) VALUES
-- Daily insights
('Summarize the key developments and conversations from today', 'summary', 'daily', 'Daily Summary', 'calendar', 1, 7, 8),
('What deals, opportunities, or projects were discussed today?', 'deals', 'daily', 'Deal Activity', 'trending-up', 2, 8, 5),
('Who were the most active people today and what did they work on?', 'people', 'daily', 'Key People', 'users', 3, 6, 5),
('What issues, problems, or concerns came up today?', 'issues', 'daily', 'Issues & Concerns', 'alert-circle', 4, 8, 5),
('What new opportunities or positive developments were mentioned today?', 'opportunities', 'daily', 'Opportunities', 'zap', 5, 7, 5),

-- Weekly insights
('What are the top 3 most important developments this week?', 'summary', 'weekly', 'Weekly Highlights', 'star', 1, 9, 10),
('Which deals or projects are progressing well this week?', 'deals', 'weekly', 'Progressing Deals', 'trending-up', 2, 8, 6),
('Which deals or projects appear to be stalling?', 'deals', 'weekly', 'Stalled Deals', 'trending-down', 3, 8, 6),
('What are the key customer conversations this week?', 'customers', 'weekly', 'Customer Activity', 'briefcase', 4, 7, 6),
('What risks or concerns emerged this week?', 'issues', 'weekly', 'Weekly Risks', 'alert-triangle', 5, 8, 6),

-- Monthly insights
('Summarize the most important business developments this month', 'summary', 'monthly', 'Monthly Overview', 'calendar', 1, 9, 12),
('Which customers were most active this month?', 'customers', 'monthly', 'Top Customers', 'users', 2, 7, 8),
('What major deals closed or progressed significantly this month?', 'deals', 'monthly', 'Deal Wins', 'check-circle', 3, 8, 8),
('What are the emerging trends or patterns this month?', 'trends', 'monthly', 'Emerging Trends', 'activity', 4, 8, 10),
('What should be the focus areas for next month?', 'recommendations', 'monthly', 'Next Month Focus', 'target', 5, 9, 8);


-- ============================================================================
-- HELPER VIEWS
-- ============================================================================

-- Latest daily insights for quick dashboard queries
CREATE OR REPLACE VIEW latest_daily_insights AS
SELECT
    tenant_id,
    insight_date,
    query_category,
    search_query,
    ai_answer,
    source_documents,
    total_sources,
    generated_at
FROM intelligence_insights
WHERE time_period = 'daily'
    AND insight_date = CURRENT_DATE
ORDER BY (
    SELECT display_order
    FROM intelligence_search_queries
    WHERE query_text = intelligence_insights.search_query
    LIMIT 1
);

-- Latest weekly insights
CREATE OR REPLACE VIEW latest_weekly_insights AS
SELECT
    tenant_id,
    insight_date,
    query_category,
    search_query,
    ai_answer,
    source_documents,
    total_sources,
    generated_at
FROM intelligence_insights
WHERE time_period = 'weekly'
    AND insight_date >= DATE_TRUNC('week', CURRENT_DATE)
ORDER BY (
    SELECT display_order
    FROM intelligence_search_queries
    WHERE query_text = intelligence_insights.search_query
    LIMIT 1
);


-- ============================================================================
-- HELPER FUNCTIONS
-- ============================================================================

-- Get all insights for a specific date
CREATE OR REPLACE FUNCTION get_insights_for_date(
    p_tenant_id TEXT,
    p_date DATE,
    p_time_period TEXT DEFAULT 'daily'
)
RETURNS TABLE (
    query_category TEXT,
    display_title TEXT,
    ai_answer TEXT,
    source_documents JSONB,
    total_sources INTEGER
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        ii.query_category,
        sq.display_title,
        ii.ai_answer,
        ii.source_documents,
        ii.total_sources
    FROM intelligence_insights ii
    LEFT JOIN intelligence_search_queries sq
        ON ii.search_query = sq.query_text
    WHERE ii.tenant_id = p_tenant_id
        AND ii.insight_date = p_date
        AND ii.time_period = p_time_period
    ORDER BY sq.display_order;
END;
$$ LANGUAGE plpgsql;


-- ============================================================================
-- NOTES
-- ============================================================================
-- 1. This replaces the old daily/weekly/monthly_intelligence tables
-- 2. Much simpler schema - just stores RAG search results
-- 3. Each insight has sources for drill-down to original docs
-- 4. Queries are configurable via intelligence_search_queries table
-- 5. Can add custom queries without migration
-- 6. Reuses existing RAG pipeline (no new infrastructure)
-- 7. Actually provides business intelligence (not just counts)
-- ============================================================================
